from __future__ import annotations

import hashlib
import os
import shutil
import time
from pathlib import Path
from threading import Lock
from urllib.parse import quote, urlsplit
from uuid import uuid4

from ..observability import event
from ..parsers import (
    MAX_FILE_BYTES,
    ParseError,
    chunks_for_sections,
    html_sections,
    parse_file,
)
from ..source_preview import canvas_html
from ..store import StudyStore
from .canvas import CanvasServiceError


def safe_external_url(value):
    try:
        parsed = urlsplit(str(value))
        if (
            parsed.scheme in {"http", "https"}
            and parsed.hostname
            and not parsed.username
            and not parsed.password
        ):
            # Strip fragments and secret-bearing query strings from third-party references.
            return parsed._replace(query="", fragment="").geturl()
    except ValueError:
        pass
    return None


class SourceService:
    def __init__(self, store: StudyStore, canvas):
        self.store, self.canvas = store, canvas
        self._lock = Lock()

    def folder(self, source_id):
        # IDs are generated by SQLite inventory/upload operations, never filenames.
        root = self.store.repository.data_dir / "sources"
        if root.is_symlink():
            raise ParseError(
                "storage_error", "Source storage cannot be a symbolic link."
            )
        folder = root / source_id
        if folder.is_symlink():
            raise ParseError(
                "storage_error", "Source storage cannot be a symbolic link."
            )
        folder.mkdir(parents=True, mode=0o700, exist_ok=True)
        os.chmod(root, 0o700)
        os.chmod(folder, 0o700)
        return folder

    def _preview_path(self, source):
        path = self.folder(source["id"]) / "canvas-preview-v1.html"
        if path.is_symlink():
            raise ParseError(
                "storage_error", "Source previews cannot be symbolic links."
            )
        return path

    def _save_preview(self, source, body):
        path = self._preview_path(source)
        path.touch(mode=0o600)
        os.chmod(path, 0o600)
        path.write_text(canvas_html(body), encoding="utf-8")

    def preview(self, workspace, source):
        kind = source["kind"]
        if kind not in {
            "syllabus",
            "page",
            "assignment",
            "discussion",
            "announcement",
        } or source["status"] not in {"ready", "stale"}:
            return None
        path = self._preview_path(source)
        if not path.exists():
            course_id, object_id = (
                workspace["canvas_course_id"],
                source["canvas_object_id"],
            )
            if kind == "syllabus":
                raw = self.canvas.client_call(
                    "get_course", course_id=course_id, include=["syllabus_body"]
                )
                body = raw.get("syllabus_body") or ""
            elif kind == "page":
                raw = self.canvas.client_call(
                    "get_page", course_id=course_id, url_or_id=object_id
                )
                body = raw.get("body") or ""
            elif kind == "assignment":
                raw = self.canvas.client_call(
                    "get_assignment", course_id=course_id, assignment_id=object_id
                )
                body = raw.get("description") or ""
            else:
                raw = self.canvas.client_call(
                    "get_discussion_topic", course_id=course_id, topic_id=object_id
                )
                body = raw.get("message") or ""
            self._save_preview(source, body)
        with path.open(encoding="utf-8") as saved:
            return saved.read(4_000_000)

    def inventory(self, workspace):
        course_id = workspace.get("canvas_course_id")
        if not course_id:
            return {"sources": self.store.sources(workspace["id"]), "warnings": []}
        base = f"https://canvas.ust.hk/courses/{course_id}"
        warnings = []

        def add(
            kind,
            identifier,
            title,
            suffix,
            raw=None,
            metadata=None,
            status="not_synced",
        ):
            raw = raw or {}
            return self.store.upsert_source(
                workspace["id"],
                {
                    "source_key": f"{kind}:{identifier}",
                    "kind": kind,
                    "canvas_object_id": str(identifier),
                    "title": str(title or "Untitled source")[:500],
                    "canvas_url": base + suffix,
                    "mime_type": raw.get("content-type") or raw.get("content_type"),
                    "remote_updated_at": raw.get("updated_at") or raw.get("posted_at"),
                    "metadata": metadata or {},
                    "status": status,
                },
            )

        # Each category is independent: a disabled discussion tab must not hide files.
        categories = [
            ("page", "list_pages", {"course_id": course_id, "limit": 300}),
            ("file", "list_files", {"course_id": course_id, "limit": 300}),
            ("assignment", "list_assignments", {"course_id": course_id, "limit": 300}),
            (
                "discussion",
                "list_discussion_topics",
                {"course_id": course_id, "limit": 300},
            ),
            (
                "announcement",
                "list_announcements",
                {"course_ids": [course_id], "active_only": False, "limit": 300},
            ),
        ]
        try:
            course = self.canvas.client_call(
                "get_course", course_id=course_id, include=["syllabus_body"]
            )
            # Even an empty syllabus is a source with an explicit extraction result.
            add(
                "syllabus",
                course_id,
                "Course syllabus",
                "/assignments/syllabus",
                course,
            )
        except CanvasServiceError as exc:
            warnings.append(
                {"category": "syllabus", "code": exc.code, "message": str(exc)}
            )
        for kind, method, args in categories:
            try:
                rows = self.canvas.client_call(method, **args)
                if len(rows) >= 300:
                    warnings.append(
                        {
                            "category": kind,
                            "code": "inventory_truncated",
                            "message": "Only the first 300 sources in this category are listed.",
                        }
                    )
                for row in rows:
                    identifier = row.get("url") if kind == "page" else row.get("id")
                    if identifier is None:
                        continue
                    if kind == "page":
                        suffix = "/pages/" + quote(str(identifier), safe="")
                    else:
                        route = {
                            "file": "files",
                            "assignment": "assignments",
                            "discussion": "discussion_topics",
                            "announcement": "discussion_topics",
                        }[kind]
                        suffix = f"/{route}/{quote(str(identifier), safe='')}"
                    metadata = (
                        {
                            "filename": row.get("filename") or row.get("display_name"),
                            "size": row.get("size"),
                        }
                        if kind == "file"
                        else {}
                    )
                    add(
                        kind,
                        identifier,
                        row.get("title")
                        or row.get("name")
                        or row.get("display_name")
                        or row.get("filename"),
                        suffix,
                        row,
                        metadata,
                    )
            except CanvasServiceError as exc:
                warnings.append(
                    {"category": kind, "code": exc.code, "message": str(exc)}
                )
        try:
            modules = self.canvas.client_call(
                "list_modules",
                course_id=course_id,
                include_items=False,
                limit=300,
                items_limit=300,
            )
            for module in modules:
                module_id = str(module.get("id"))
                items = []
                # Canvas can return a partial inline items array even when the
                # module itself is complete. Always read the canonical endpoint.
                try:
                    module_items = self.canvas.client_call(
                        "activity_list",
                        endpoint=f"courses/{course_id}/modules/{module_id}/items",
                        params={"include": ["content_details"]},
                        limit=300,
                    )
                except CanvasServiceError as exc:
                    warnings.append(
                        {"category": "module", "code": exc.code, "message": str(exc)}
                    )
                    continue
                if module_items.get("truncated"):
                    warnings.append(
                        {
                            "category": "module",
                            "code": "inventory_truncated",
                            "message": "A module has more than 300 items; its source tree is partial.",
                        }
                    )
                known_keys = {
                    s["source_key"] for s in self.store.sources(workspace["id"])
                }
                for item in module_items.get("items", []):
                    kind = str(item.get("type", ""))
                    key_kind = {
                        "Page": "page",
                        "File": "file",
                        "Assignment": "assignment",
                        "Discussion": "discussion",
                    }.get(kind)
                    object_id = (
                        item.get("page_url")
                        if kind == "Page"
                        else item.get("content_id")
                    )
                    record = {
                        "id": str(item.get("id")),
                        "title": str(item.get("title", ""))[:500],
                        "type": kind,
                    }
                    if key_kind and object_id is not None:
                        record["source_key"] = f"{key_kind}:{object_id}"
                        if record["source_key"] not in known_keys:
                            route = {
                                "page": "pages",
                                "file": "files",
                                "assignment": "assignments",
                                "discussion": "discussion_topics",
                            }[key_kind]
                            add(
                                key_kind,
                                object_id,
                                item.get("title"),
                                f"/{route}/{quote(str(object_id), safe='')}",
                            )
                            known_keys.add(record["source_key"])
                    if kind in {"ExternalUrl", "ExternalTool"}:
                        external = add(
                            "external",
                            item.get("id"),
                            item.get("title"),
                            f"/modules/items/{item.get('id')}",
                            metadata={
                                "external_url": safe_external_url(
                                    item.get("external_url")
                                ),
                                "module": str(module.get("name", ""))[:500],
                            },
                            status="external_reference",
                        )
                        record["source_key"] = external["source_key"]
                    items.append(record)
                add(
                    "module",
                    module_id,
                    module.get("name"),
                    f"/modules/{module_id}",
                    module,
                    {"items": items, "truncated": bool(module_items.get("truncated"))},
                )
            if len(modules) >= 300:
                warnings.append(
                    {
                        "category": "module",
                        "code": "inventory_truncated",
                        "message": "Only the first 300 modules are listed.",
                    }
                )
        except CanvasServiceError as exc:
            warnings.append(
                {"category": "module", "code": exc.code, "message": str(exc)}
            )
        return {"sources": self.store.sources(workspace["id"]), "warnings": warnings}

    def sync(self, workspace, source_ids, *, force=False):
        if not self._lock.acquire(blocking=False):
            raise CanvasServiceError(
                "sync_in_progress", "Another sync is in progress. Please wait.", 409
            )
        try:
            results = []
            for identifier in source_ids:
                source = self.store.source(workspace["id"], identifier)
                if source is None:
                    raise CanvasServiceError(
                        "source_not_found", "Source not found in this workspace.", 404
                    )
                results.append(self._sync_one(workspace, source, force))
            return {"sources": results}
        finally:
            self._lock.release()

    def _sync_one(self, workspace, source, force):
        started = time.monotonic()
        if source["status"] == "external_reference" or source["kind"] == "upload":
            return source
        self.store.source_status(source["id"], "syncing")
        try:
            course_id, kind, object_id = (
                workspace["canvas_course_id"],
                source["kind"],
                source["canvas_object_id"],
            )
            if kind == "file":
                metadata = self.canvas.client_call(
                    "get_file", course_id=course_id, file_id=object_id
                )
                remote = metadata.get("updated_at")
                if (
                    not force
                    and source["checksum"]
                    and remote
                    and remote == source["synced_remote_updated_at"]
                ):
                    self.store.source_status(source["id"], "ready")
                    return self.store.source(workspace["id"], source["id"])
                if int(metadata.get("size") or 0) > MAX_FILE_BYTES:
                    raise ParseError("file_too_large", "Files must be at most 25 MB.")
                suffix = Path(
                    str(metadata.get("filename") or metadata.get("display_name") or "")
                ).suffix.lower()
                from ..parsers import SUPPORTED

                if suffix not in SUPPORTED:
                    raise ParseError(
                        "unsupported_format",
                        "This file type is a reference only. Videos require an uploaded caption file.",
                    )
                source = self.store.upsert_source(
                    workspace["id"], {**source, "remote_updated_at": remote}
                )
                path = self.folder(source["id"]) / ("original" + suffix)
                # Create private permissions before writing any downloaded bytes.
                if path.is_symlink():
                    raise ParseError(
                        "storage_error", "Source files cannot be symbolic links."
                    )
                path.touch(mode=0o600)
                os.chmod(path, 0o600)
                self.canvas.client_call(
                    "download_file_bounded",
                    course_id=course_id,
                    file_id=object_id,
                    destination_path=str(path),
                    max_bytes=MAX_FILE_BYTES,
                )
                checksum = hashlib.sha256(path.read_bytes()).hexdigest()
                if not force and checksum == source["checksum"]:
                    self._revalidate(source)
                else:
                    self.store.index(source, parse_file(path, suffix), checksum)
            else:
                if kind == "syllabus":
                    raw = self.canvas.client_call(
                        "get_course", course_id=course_id, include=["syllabus_body"]
                    )
                    body = raw.get("syllabus_body") or ""
                elif kind == "page":
                    raw = self.canvas.client_call(
                        "get_page", course_id=course_id, url_or_id=object_id
                    )
                    body = raw.get("body") or ""
                elif kind == "assignment":
                    raw = self.canvas.client_call(
                        "get_assignment", course_id=course_id, assignment_id=object_id
                    )
                    body = raw.get("description") or ""
                elif kind in {"discussion", "announcement"}:
                    raw = self.canvas.client_call(
                        "get_discussion_topic", course_id=course_id, topic_id=object_id
                    )
                    body = raw.get("message") or ""
                elif kind == "module":
                    raw = self.canvas.client_call(
                        "activity_get",
                        endpoint=f"courses/{course_id}/modules/{object_id}",
                    )
                    current = self.canvas.client_call(
                        "activity_list",
                        endpoint=f"courses/{course_id}/modules/{object_id}/items",
                        params={"include": ["content_details"]},
                        limit=300,
                    )
                    items = []
                    for item in current["items"]:
                        item_kind = str(item.get("type", ""))
                        key_kind = {
                            "Page": "page",
                            "File": "file",
                            "Assignment": "assignment",
                            "Discussion": "discussion",
                            "ExternalUrl": "external",
                            "ExternalTool": "external",
                        }.get(item_kind)
                        item_object = (
                            item.get("page_url")
                            if item_kind == "Page"
                            else item.get("id")
                            if key_kind == "external"
                            else item.get("content_id")
                        )
                        record = {
                            "id": str(item.get("id")),
                            "title": str(item.get("title", ""))[:500],
                            "type": item_kind,
                        }
                        if key_kind and item_object is not None:
                            record["source_key"] = f"{key_kind}:{item_object}"
                        items.append(record)
                    source = self.store.upsert_source(
                        workspace["id"],
                        {
                            **source,
                            "title": raw.get("name") or source["title"],
                            "metadata": {
                                "items": items,
                                "truncated": bool(current.get("truncated")),
                            },
                        },
                    )
                    body = (
                        source["title"]
                        + "\n"
                        + "\n".join(f"{i['title']} ({i['type']})" for i in items)
                    )
                else:
                    raise ParseError(
                        "unsupported_format", "This source type cannot be indexed."
                    )
                if kind != "module":
                    self._save_preview(source, body)
                checksum = hashlib.sha256(body.encode()).hexdigest()
                source = self.store.upsert_source(
                    workspace["id"],
                    {
                        **source,
                        "remote_updated_at": raw.get("updated_at")
                        or raw.get("posted_at"),
                    },
                )
                if not force and checksum == source["checksum"]:
                    self._revalidate(source)
                else:
                    sections = html_sections(body)
                    if kind == "module":
                        sections = [
                            (
                                source["title"],
                                {"module_id": object_id, "heading": source["title"]},
                            )
                        ] + [
                            (
                                i["title"] + " (" + i["type"] + ")",
                                {
                                    "module_id": object_id,
                                    "item_id": i["id"],
                                    "heading": source["title"],
                                },
                            )
                            for i in source["metadata"].get("items", [])
                        ]
                    self.store.index(source, chunks_for_sections(sections), checksum)
            self._write_text(source)
        except (ParseError, CanvasServiceError) as exc:
            self.store.source_status(
                source["id"],
                "unsupported"
                if exc.code in {"unsupported_format", "no_extractable_text"}
                else "failed",
                code=exc.code,
                message=str(exc),
            )
        except Exception:  # noqa: BLE001 -- malformed source errors never reveal private contents/paths
            self.store.source_status(
                source["id"],
                "failed",
                code="sync_failed",
                message="This source could not be indexed. Retry or upload a supported document.",
            )
        result = self.store.source(workspace["id"], source["id"])
        event(
            "source_sync",
            kind=source["kind"],
            status=result["status"],
            code=result.get("error_code"),
            elapsed_ms=int((time.monotonic() - started) * 1000),
        )
        return result

    def _revalidate(self, source):
        # Preserve chunk IDs: saved citations must continue to resolve on an unchanged refresh.
        from contextlib import closing

        from ..db import now

        with closing(self.store.repository._connect()) as db, db:
            db.execute(
                """UPDATE sources SET status='ready',synced_remote_updated_at=remote_updated_at,
                last_sync_at=?,updated_at=?,error_code=NULL,error_message=NULL WHERE id=?""",
                (now(), now(), source["id"]),
            )

    def _write_text(self, source):
        path = self.folder(source["id"]) / "extracted.txt"
        if path.is_symlink():
            raise ParseError("storage_error", "Source files cannot be symbolic links.")
        path.touch(mode=0o600)
        os.chmod(path, 0o600)
        path.write_text(
            "\n\n".join(
                c["text"]
                for c in self.store.chunks(source["workspace_id"], source["id"])
            ),
            encoding="utf-8",
        )

    def upload(self, workspace_id, filename, data):
        if len(data) > MAX_FILE_BYTES:
            raise ParseError("file_too_large", "Files must be at most 25 MB.")
        filename = Path(filename.replace("\\", "/")).name[:200] or "Untitled upload"
        suffix = Path(filename).suffix.lower()
        source = self.store.upsert_source(
            workspace_id,
            {
                "source_key": "upload:" + str(uuid4()),
                "kind": "upload",
                "title": filename,
                "metadata": {"filename": filename, "size": len(data)},
                "status": "syncing",
            },
        )
        try:
            path = self.folder(source["id"]) / (
                "original" + suffix
                if suffix
                in {
                    ".txt",
                    ".md",
                    ".html",
                    ".htm",
                    ".pdf",
                    ".docx",
                    ".pptx",
                    ".vtt",
                    ".srt",
                }
                else "original.bin"
            )
            if path.is_symlink():
                raise ParseError(
                    "storage_error", "Source files cannot be symbolic links."
                )
            path.touch(mode=0o600)
            os.chmod(path, 0o600)
            path.write_bytes(data)
            self.store.index(
                source, parse_file(path, suffix), hashlib.sha256(data).hexdigest()
            )
            self._write_text(source)
        except ParseError as exc:
            self.store.source_status(
                source["id"],
                "unsupported"
                if exc.code in {"unsupported_format", "no_extractable_text"}
                else "failed",
                code=exc.code,
                message=str(exc),
            )
        return self.store.source(workspace_id, source["id"])

    def remove_files(self, source_id):
        folder = self.store.repository.data_dir / "sources" / source_id
        if folder.is_dir() and not folder.is_symlink():
            shutil.rmtree(folder)
